// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWLqqbkpZcRWtTUoubKq2zbQfMhG7GR0A',
    appId: '1:531558083130:web:e6dd845c89b0825a752303',
    messagingSenderId: '531558083130',
    projectId: 'teachmap-80e32',
    authDomain: 'teachmap-80e32.firebaseapp.com',
    storageBucket: 'teachmap-80e32.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF2CuxJE_wap_BmvhE266BloenQcEQrFw',
    appId: '1:531558083130:android:420901ba760b63d0752303',
    messagingSenderId: '531558083130',
    projectId: 'teachmap-80e32',
    storageBucket: 'teachmap-80e32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZV_bsPg7bYLfIGQebhCerPiiFvcOqP2A',
    appId: '1:531558083130:ios:1ddabe8913bbd0f8752303',
    messagingSenderId: '531558083130',
    projectId: 'teachmap-80e32',
    storageBucket: 'teachmap-80e32.firebasestorage.app',
    iosBundleId: 'com.example.teachmap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZV_bsPg7bYLfIGQebhCerPiiFvcOqP2A',
    appId: '1:531558083130:ios:1ddabe8913bbd0f8752303',
    messagingSenderId: '531558083130',
    projectId: 'teachmap-80e32',
    storageBucket: 'teachmap-80e32.firebasestorage.app',
    iosBundleId: 'com.example.teachmap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWLqqbkpZcRWtTUoubKq2zbQfMhG7GR0A',
    appId: '1:531558083130:web:6f2718ab03c7f18b752303',
    messagingSenderId: '531558083130',
    projectId: 'teachmap-80e32',
    authDomain: 'teachmap-80e32.firebaseapp.com',
    storageBucket: 'teachmap-80e32.firebasestorage.app',
  );
}
